[package]
name = "support"
version = "0.1.0"
edition = "2021"

[dependencies]
lib = { path = "../support/lib" }
axum = "0.6"
tokio = { version = "1", features = ["full"] }
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
dotenv = "0.15"