[package]
edition = "2021"
name = "support"
version = "0.1.0"

[dependencies]
axum = "0.6"
dotenv = "0.15"
lib = {path = "../support/lib"}
tokio = {version = "1", features = ["full"]}
tracing = "0.1"
tracing-subscriber = {version = "0.3", features = ["env-filter"]}
